version: 2

sources:
  - name: retail_source
    database: retail_db
    schema: public

    tables:
      - name: fact_orders
      - name: dim_customers

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null